import { Inter } from 'next/font/google'
import Head from 'next/head'
import HomeIntro from '@/components/HomeIntro'
import HomeBlog from '@/components/HomeBlog'
import HomeWork from '@/components/HomeWork'
import { allWorks, getAllPosts } from '@/lib/api';

const inter = Inter({ subsets: ['latin'] })

export async function getStaticProps() {
  const posts = getAllPosts();
  const works = allWorks();

  return {
    props: {
      posts,
      works
    },
  };
}



export default function Home({ posts, works }) {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className=''>
        <HomeIntro></HomeIntro>
        <HomeBlog posts={posts}></HomeBlog>
        <HomeWork works={works}></HomeWork>
      </main>

    </>
  )
}
